# Read the Docs configuration file
version: 2


build:
os: ubuntu-22.04
tools:
python: "3.11"
jobs:
post_create_environment:
- pip install -r requirements.txt


sphinx:
configuration: conf.py


formats:
- htmlzip
- pdf